### ISSUE TITLE
libgemma.a usage?

### ISSUE THREAD

**Issue by vinriviere** [freemint/gemma#1]
I'm not sure to understand what the static library `libgemma.a` is.
The file `README.FIRST` says:

> This is the statically linked part of the gemma32.slb which gateways
> the application to the shared object.

I understand that `gemma32.slb` is always dynamically linked, but that `libgemma.a` does the glue part so applications don't have to directly deal wth SLB stuff.

By looking at `include/slb/gemma.h`, I see familiar stuff:
> extern long appl_init(void);
> extern long appl_read(short ApId, short Length, void *ApPbuff);

Is `libgemma.a` also supposed to be a GemLib alternative? Or do I miss something?

**Comment by th-otto** [comment]
That's the solution of our poor a.out target not being able to link to shared libs directly. Actually the program does not "link" to the slb at all, its more similar to dynamically loading an object using dlopen/dlsym on unix.

You need code in your application to explicitly load it, and call the defined functions. Every SLB essentially works this way. In kernel32 for example, a slightly different approach was taken, by putting the "glue" functions into inline functions, that's why you don't need a static library there.

**Comment by vinriviere** [comment]
That makes sense.
And about function names similar to GemLib ones?

**Comment by th-otto** [comment]
I think this is done because gemma.slb maintains an AES global array per process using it, so the bindings are there to ensure that the application itself is using the same array.

**Comment by mikrosk** [comment]
I guess this qualifies as explained. :-)

**Comment by vinriviere** [comment]
So, as a conclusion, how are we supposed to use libgemma?
More specifically: is appl_init() implemented in libgemma.a? If so, do we need to also link with libgem.a? Will there be name conflicts ar linking time?
It is really weird to see functions in a library (gemma) with the same names as in other one (gem).

**Comment by th-otto** [comment]
Hm, why didn't you ask this last year, when i was working on it? Now i have to dig into the source again :(

Q: how are we supposed to use libgemma?
A: similar to cflib. Additionally it also directly implements some gemlib calls, saving codespace if all libraries used by the application also use libgemma.

Q: is appl_init() implemented in libgemma.a?
A: yes

Q: If so, do we need to also link with libgem.a?
A: Yes. Not all AES functions from gemlib are also implemented in gemma. And none of the vdi functions.

Q: Will there be name conflicts at linking time?
A: I don't hope so, and i don't think so. Just have to make sure that libgemma is linked first, if you need both. Hard to tell since i know of only two programs so far that use it, gemma's own configuration tool and and gemkfatfs.

>It is really weird to see functions in a library (gemma) with the same names as in other one (gem).

But thats the whole purpose of such a shared lib, ideally just using different header files, and an additional library, and don't have to change anything in your code to use it.

**Comment by vinriviere** [comment]
Sorry, I missed your comment last year.
OK, so rule is: put `-lgemma` before `-lgem` on the linker command line and everrything will be fine. And cross our fingers that the appli_init() declaration (and other functions) in gemma.h don't conflict with the ones in gemlib.
Thanks for your analysis, @th-otto. As everything is now answered, I close this issue.
